### ISSUE TITLE
"Footnotes" heading created when publishing

### ISSUE THREAD

**Issue by contrapunctus-1** [ox-tufte/ox-tufte#12]
If I use `:publishing-function org-html-export-to-tufte-html` in my `org-publish-project-alist` and then call `org-publish-project`, the resulting HTML has a "Footnotes" heading with the footnotes.

Steps -
1. `emacs -q`
2. Create an Org file -
   ```org
   * a heading
   some text [fn:1]

   [fn:1] a footnote
   ```
3. Evaluate
   ```elisp
   (require 'ox-publish)
   (require 'ox-tufte)
   (setq org-publish-project-alist
         '(("test"
             :base-directory "/test/path/"
             :publishing-directory "/test/path/"
             :publishing-function org-html-publish-to-tufte-html))
         org-tufte-include-footnotes-at-bottom nil)
   ```
4. `M-x org-publish RET test RET`

Thank you so much for creating `ox-tufte`. I'm very happy with the results of using it on [my website](https://contrapunctus.codeberg.page/).

**Comment by bayesians-inc-PL** [comment]
this is resolved in the upcoming release (v2). note, however, that v2 is backwards incompatible with v1. to overcome the issue in v1, you can do something like:
```elisp
(setq org-html-footnotes-section "<!-- %s --><!-- %s -->")
```

**Comment by bayesians-inc-PL** [comment]
in the upcoming release (currently available for preview on the `dev` branch), this is fixed. see https://github.com/ox-tufte/ox-tufte/tree/dev#footnotes-section-at-bottom for usage
