### ISSUE TITLE
Documentation: Fix stray END_FIGURE in Fullwidth figures sample code

### ISSUE THREAD

**Issue by cceddie** [ox-tufte/ox-tufte#18]
In the readme file, I believe the sample code for fullwidth figures is missing #+BEGIN_FIGURE in the sample code.  Without it, the END FIGURE ends up getting rendered in the HTML export.

Suggested:
```
#+ATTR_HTML: :class fullwidth
#+BEGIN_FIGURE
#+CAPTION: Edward Tufte’s English translation...
[[https://edwardtufte.github.io/tufte-css/img/napoleons-march.png]]
#+end_figure
```
 
 
Current:
```
#+ATTR_HTML: :class fullwidth
#+CAPTION: Edward Tufte’s English translation...
[[https://edwardtufte.github.io/tufte-css/img/napoleons-march.png]]
#+end_figure
```

**Comment by bayesians-inc-PL** [comment]
good catch. yes, the example in the `README` is incorrect. strictly speaking, for `fullwidth` you don't even need to have `#+begin_figure` and `#+end_figure`. so there are two variations. i'll update the README shortly
