### ISSUE TITLE
Tufte Image Quilt

### ISSUE THREAD

**Issue by jonnay** [ox-tufte/ox-tufte#5]
I have been thinking about how one would support a Tufte image quilt. Something like:

```
#+begin_tufte_quilt
file:./quilt/foo.png
http://example.com/bar.png
#+end_tufte_quilt
```

One could assume (at the start anyway) imagemagick is compiled to scale the images down to a constant height, and then probably use an overlay to display the images overtop of the quilt definition.  Or should it be below?  Not sure.

org-fstree uses a similar pattern: https://melpa.org/#/org-fstree

Not sure how this would play out with the exporter.

What do you think?

**Comment by dakrone** [comment]
So right now, looking at the tufte-css source, the image quilt examples that are
posted are actually only a single image, so that doesn't really explain how to
use them. I think this warrants perhaps more research on how to combine multiple
images on the page rather than pre-processing them into a single image first
(thought that may be the ultimate solution).

**Comment by jonnay** [comment]
I'm just kinda playing around right now, but this is what I have:

Org/elisp:

```
#+begin_src emacs-lisp :results html :exports both
(concat "<div class=\"my-quilt\">\n"      
        (mapconcat (lambda (f)
                     (format "  <img src=\"./assets/images/tome-quilt/%s\" />\n" f))
                   (directory-files "assets/images/tome-quilt"
                                    nil
                                    (regexp-opt '("jpg" "jpeg" "png" "gif")))
                   "")
        "</div>\n")
#+end_src
```

CSS:
```css
.my-quilt {
  margin: 4rem 0;
  text-align: center;
  font-size: 0;
}

.my-quilt img {
  max-height: 200px;
  min-height: 200px;
  display: inline-block;
}
```

It produces a ragged edge quilt.  I am pulling the margin and the height values out of thin air.

The problem here is that this requires extra CSS.

**Comment by jonnay** [comment]
Here is a sample: http://jonnay.github.io/emagicians-starter-kit/Emagician-Meta.html#orgheadline17

**Comment by dakrone** [comment]
The extra CSS is probably something that could be added to the element itself, rather than having to add it to CSS

Maybe then it could be attributes on the block, like:

```
#+BEGIN_TUFTE_QUILT :max-height 200 :min-height 100
/path/to/img1.jpg
/path/to/img2.jpg
/another/img.png
#+END_TUFTE_QUILT
```

**Comment by bayesians-inc-PL** [comment]
in [the upcoming v2 release](https://github.com/ox-tufte/ox-tufte/milestone/1), below is possible:
```org
#+HTML_HEAD_EXTRA: <style> .quiltish img { max-height: 200px; min-height: 100px; } </style>
#+attr_html: :class quiltish
#+CAPTION: caption for multiple images
#+begin_figure
[[./path/to/img1.png]]
[[./path/to/img2.png]]
#+end_figure
```

the v2 release is now available for preview at https://github.com/ox-tufte/ox-tufte/tree/dev .
once https://github.com/melpa/melpa/pull/8633 is merged then v2 can be released.
