### ISSUE TITLE
CSS included?

### ISSUE THREAD

**Issue by alphapapa** [ox-tufte/ox-tufte#8]
Hi,

This looks like a neat project.  I'm curious, why isn't the CSS included in this package?  Leaving it out means that users have to keep a copy of it themselves and manually put it in the export directory, and if the web site where it's stored were down, they wouldn't be able to retrieve it.  If it was built-in, users could use the "export and open" option and have the browser display it correctly immediately, and then publish directly without having to retrieve the CSS and place it manually.

**Comment by dakrone** [comment]
alphapapa writes:

> Hi,
>
> This looks like a neat project. I'm curious, why isn't the CSS
> included in this package? Leaving it out means that users have to keep
> a copy of it themselves and manually put it in the export directory,
> and if the web site where it's stored were down, they wouldn't be able
> to retrieve it. If it was built-in, users could use the "export and
> open" option and have the browser display it correctly immediately,
> and then publish directly without having to retrieve the CSS and place
> it manually.

Yeah, I'm kind of on the fence with this. It would be nice to bundle it
with the project, but on the other hand, tufte-css is pretty large due
to including fonts as part of the package, so I didn't want to have a
giant binary distribution for an elisp package.

For now, I went with the style I saw in org-reveal, which was to require
downloading it. I *do* think it'd be useful to have a way to open it
locally though, any assistance with this is appreciated!

--
;; Lee

**Comment by alphapapa** [comment]
Yeah, I noticed the fonts after I posted this.  :)  That's definitely an issue; I don't blame you for not wanting to include those.

> I *do* think it'd be useful to have a way to open it locally though, any assistance with this is appreciated!

Do you mean something like a function to download it from within Emacs?  I guess that would be simple enough.  Might be good to keep a hash of the file so it can be verified to match, although if it changes often on their end, that could become a problem.  Although, since it's on GitHub, a specific revision could be fetched, so that would solve that.  And it could still encourage the user to download the latest version manually, along with the fonts.

**Comment by dakrone** [comment]
alphapapa writes:

> Do you mean something like a function to download it from within
> Emacs? I guess that would be simple enough. Might be good to keep a
> hash of the file so it can be verified to match, although if it
> changes often on their end, that could become a problem. Although,
> since it's on GitHub, a specific revision could be fetched, so that
> would solve that. And it could still encourage the user to download
> the latest version manually, along with the fonts.

Yeah a function could probably be a good way to do it. We could probably
add a defcustom that pointed to "v1.1" that would download the specific
version from https://github.com/edwardtufte/tufte-css/releases (and of
course, always let the user download it manually, as you said).

--
;; Lee

**Comment by bayesians-inc-PL** [comment]
[the readme in upcoming version](https://github.com/ox-tufte/ox-tufte/tree/dev#installation-and-usage) specifically links to [the v1.8.0 release](https://github.com/edwardtufte/tufte-css/releases/tag/v1.8.0). since manually downloading it has about as many manual steps as would be needed if a function were provided to download it, this likely won't be fixed unless there are standard conventions that can be safely assumed about the user's site layout.
