### ISSUE TITLE
No margin or footnote in side for headers?

### ISSUE THREAD

**Issue by borgauf** [ox-tufte/ox-tufte#9]
Apparently it is not possible to have a footnote or margin note appear in the second side column if it is attached to a starred header, correct? I have an org-mode style where everything is a heading, i.e., a starred entry. That way upon export to HTML, every separate starred line has its own outline-styled numbering. Very orderly looking, IMHO. Also, because everything is a header with me, long lines do not seem to wrap with ox-tufte. I'm saying anything with a star doesn't conform to the main first column width. One more problem would be how latex formatted math, e.g.

\begin{align}
0! = 1\\ 
(n+1)! = (n+1) \cdot n! \\
\end{align}

also doesn't do first main column, rather, text aligns "center" and stretches across the page. Otherwise, this is great and I duly appreciate.

[recurstest.org.txt](https://github.com/dakrone/ox-tufte/files/818765/recurstest.org.txt)

**Comment by dakrone** [comment]
@borgauf thanks for reporting this, I'll take a look!

**Comment by borgauf** [comment]
Thank. Again, the only way to have a footnote appear in the second column is to not have any outlining whatsoever, not heading (stars) or any sort of [http://orgmode.org/manual/Plain-lists.html](url) plain list outlining under a starred heading.

**Comment by bayesians-inc-PL** [comment]
in [v2](https://github.com/ox-tufte/ox-tufte/milestone/1), it is now possible to have footnotes on headings:
```org
* A Heading[fn::This is a sidenote associated with the heading.]
Text under the heading ...
```

the v2 release is now available for preview at https://github.com/ox-tufte/ox-tufte/tree/dev .
once https://github.com/melpa/melpa/pull/8633 is merged, then [v2](https://github.com/ox-tufte/ox-tufte/milestone/1) could be released.
